### ISSUE TITLE
Icons for .toml Files and Bun Files

### ISSUE THREAD

**Issue by Barzi-Ahmed** [monokai-pro/vscode#393]
Hello, 
Kudos for this great theme. 

Please add icons for .toml files, and [Bun](https://bun.sh/)-related files (e.g. .lockb). 

![n](https://github.com/Monokai/monokai-pro-vscode/assets/135956133/345c59cd-67a8-4925-9946-f884a998c722)
![a](https://github.com/Monokai/monokai-pro-vscode/assets/135956133/5ce6cf6f-1fa1-4b1d-9590-ff49e095dad2)

**Comment by Monokai** [comment]
In the meantime this has been fixed
