### ISSUE TITLE
Fixed the highlight line (dividing line) of code cell in python file

### ISSUE THREAD

**Issue by idlesilver** [monokai-pro/vscode#400]
The problem has be mentioned in https://github.com/Monokai/monokai-pro-vscode/issues/173#issue-577287699 and https://github.com/microsoft/vscode/issues/99425#issue-631358442. The reason is missing two color configuration: `interactive.activeCodeBorder` and `interactive.inactiveCodeBorder`. You can fix it by adding the following configuration in the setting file. The selected line highlight can be handled with `editor.lineHighlightBorder`

```json
    "workbench.colorCustomizations": {
        "[Monokai*]": {
            "editor.lineHighlightBorder": "#c1c0c070",
            "interactive.activeCodeBorder": "#fcfcfad0",
            "interactive.inactiveCodeBorder": "#c1c0c0",
        }
    },
```
Here is how it looks

![image](https://github.com/Monokai/monokai-pro-vscode/assets/47479230/402c8e4f-16df-42ee-9966-66890d3d398a)

**Comment by Monokai** [comment]
fixed in 1.3.0
