### ISSUE TITLE
Color Scheme seems different than advertised in images

### ISSUE THREAD

**Issue by LilSelvag07** [monokai-pro/vscode#407]
I noticed that the brackets and so on are not greyed out like the images or others vscode. Mine look like this.
![Monokai pro images](https://github.com/Monokai/monokai-pro-vscode/assets/170060833/c576536b-e4b6-4b23-a391-b058073102eb)

Along with a few other differences in color. Is this just me or a settings I have not been able to find?

Thank you,
Andrew

**Comment by Monokai** [comment]
The coloring of matching brackets is a setting in VSCode. You might want to turn that off to get the default dimmed brackets.
