### ISSUE TITLE
Bun Icon is Incorrectly Applied to "bun.lockdb" Instead of "bun.lockb"

### ISSUE THREAD

**Issue by Barzi-Ahmed** [monokai-pro/vscode#409]
Running bun install will create a binary lockfile called **bun.lockb**, but Monokai Pro VSCode icon theme doesn't apply the icon to this filename, instead it applies to **bun.lockdb** which doesn't exist and bun never produces such file.

**Comment by Monokai** [comment]
Fixed in 2.0.0
