### ISSUE TITLE
Low contrast branch label in source control graph after 1.94 Update

### ISSUE THREAD

**Issue by youyoumu** [monokai-pro/vscode#418]
Release note: https://code.visualstudio.com/updates/v1_94#_source-control

On default vscode theme:
![image](https://github.com/user-attachments/assets/d01656e1-880a-4201-964b-5c4ce87b0004)

On Monokai Pro theme:
![image](https://github.com/user-attachments/assets/1d4f6577-1c2f-4fbb-877f-1e31d805cc68)

**Comment by DolphinDream** [comment]
Yes.. I experienced this too

![Screenshot 2024-10-08 104830](https://github.com/user-attachments/assets/c9dfeebd-84e4-45f9-b012-f48f83693574)

![Screenshot 2024-10-08 105136](https://github.com/user-attachments/assets/9cbe80e0-2c33-40f1-ad49-2b7eecd6d189)

**Comment by awgv** [comment]
Didn’t dig too deep into this, but you can override these colors in your `settings.json`:

1. `Ctrl`+`Shift`+`P`
2. Select `Preferences: Open User Settings (JSON)`
3. Add the following, although, you might already have the `workbench.colorCustomizations` key:

```JSON
"workbench.colorCustomizations": {
  "scmGraph.historyItemHoverLabelForeground": "#000000",
  "scmGraph.historyItemHoverDefaultLabelForeground": "#000000"
},
```

**Comment by Monokai** [comment]
Has been fixed in the meantime
