### ISSUE TITLE
Editor widget colors too similar to editor backgound in light theme

### ISSUE THREAD

**Issue by LawrenceLiu023** [monokai-pro/vscode#422]
![image](https://github.com/user-attachments/assets/fa6b3cdb-8e2b-4800-9eb3-1c60edd81283)

I was using Monokai Pro v2.0.1 light theme, and noticed that the colours of editor widget background and border are too similar to the colour of editor background. This makes it a little difficult to distinguish the widget contents from the editor contents. It would be helpful to adjust the colours for properties such as "editorWidget.background" and "editorWidget.border".

**Comment by Monokai** [comment]
Has been adjusted in the meantime, thanks!
